// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcvTbw3kwQjmfntmQGk3jSOYudd1q51_k',
    appId: '1:498637212523:web:2035557b790e53e9135a2e',
    messagingSenderId: '498637212523',
    projectId: 'tarumt-bus',
    authDomain: 'tarumt-bus.firebaseapp.com',
    storageBucket: 'tarumt-bus.firebasestorage.app',
    measurementId: 'G-4VFGL0N30S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc-fEknNyHO1dfHFZX6TGPeUZdMeNp5XE',
    appId: '1:498637212523:android:1e604583da625746135a2e',
    messagingSenderId: '498637212523',
    projectId: 'tarumt-bus',
    storageBucket: 'tarumt-bus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArNG1ILpbWBA71QPEBwyxWIsNLxcpv0os',
    appId: '1:498637212523:ios:382d4a19e1590c07135a2e',
    messagingSenderId: '498637212523',
    projectId: 'tarumt-bus',
    storageBucket: 'tarumt-bus.firebasestorage.app',
    iosBundleId: 'com.example.tarumtBusTracking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArNG1ILpbWBA71QPEBwyxWIsNLxcpv0os',
    appId: '1:498637212523:ios:382d4a19e1590c07135a2e',
    messagingSenderId: '498637212523',
    projectId: 'tarumt-bus',
    storageBucket: 'tarumt-bus.firebasestorage.app',
    iosBundleId: 'com.example.tarumtBusTracking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcvTbw3kwQjmfntmQGk3jSOYudd1q51_k',
    appId: '1:498637212523:web:ea2a9c8436ea539c135a2e',
    messagingSenderId: '498637212523',
    projectId: 'tarumt-bus',
    authDomain: 'tarumt-bus.firebaseapp.com',
    storageBucket: 'tarumt-bus.firebasestorage.app',
    measurementId: 'G-3NGCK4Y876',
  );
}
